"""
Seed the Practice Library with actionable improvement recommendations
for each subdomain at each maturity transition (1→2, 2→3, 3→4, 4→5).
"""
import os, sys
os.environ.setdefault("LOCAL_DEV_MODE", "true")
sys.path.insert(0, os.path.dirname(__file__))

from database import SessionLocal
from models_v2 import Practice, Subdomain

# ── Practice definitions keyed by subdomain code ──
# Each entry: (title, description, from_level, to_level, impact, effort, timeline, is_critical, success_metrics, tools)
PRACTICES = {
    # ═════════ WC — Workforce Capability ═════════
    "WC.1": [  # Technical Competency
        ("Develop Skills Gap Assessment Process",
         "Create a structured process to assess current workforce technical skills against role requirements. Map competencies for each maintenance role and identify priority gaps.",
         1, 2, "high", "medium", "3-6 months", True,
         ["Skills matrix completion >90%", "Gap analysis documented for all roles"],
         ["Skills matrix template", "Competency assessment forms"]),
        ("Implement Role-Based Certification Program",
         "Establish minimum technical qualifications for each maintenance role with testing and certification requirements. Include mechanical, electrical, and instrumentation tracks.",
         2, 3, "high", "high", "6-12 months", True,
         ["100% of technicians assessed", "Certification pass rate >80%"],
         ["Certification test bank", "Training record tracker"]),
        ("Deploy Cross-Training & Multi-Skill Development",
         "Implement structured cross-training rotations so technicians develop competency across multiple crafts. Track proficiency progression and incentivize multi-skill development.",
         3, 4, "medium", "medium", "12-18 months", False,
         ["Multi-skilled ratio >40%", "Cross-training hours per tech >40/year"],
         ["Cross-training matrix", "Skill tracking dashboard"]),
        ("Establish Subject Matter Expert (SME) Program",
         "Identify and develop SMEs in critical equipment areas. Create formal mentorship pathways and knowledge capture processes for tacit knowledge transfer.",
         4, 5, "medium", "low", "6-12 months", False,
         ["SME identified for each critical asset class", "Mentorship participation >60%"],
         ["SME development program guide", "Knowledge capture templates"]),
    ],
    "WC.2": [  # Training & Development
        ("Create Structured OJT (On-the-Job Training) Program",
         "Move from informal buddy training to documented OJT with standard task lists, competency checkoffs, and trainer qualifications.",
         1, 2, "high", "medium", "3-6 months", True,
         ["OJT program documented", "All new hires complete OJT within 90 days"],
         ["OJT task checklist templates", "Trainer qualification criteria"]),
        ("Implement Blended Learning Curriculum",
         "Develop a structured annual training plan combining classroom, hands-on, e-learning, and vendor training. Align with skills gap analysis results.",
         2, 3, "high", "high", "6-12 months", False,
         ["Annual training hours >40/person", "Training plan completion >85%"],
         ["LMS integration guide", "Annual training calendar template"]),
        ("Establish Training Effectiveness Measurement",
         "Implement Kirkpatrick Level 3-4 evaluation to measure on-the-job application of training and business impact. Track correlation between training investment and equipment performance.",
         3, 4, "medium", "medium", "6-12 months", False,
         ["Training ROI tracked quarterly", "Performance improvement linked to training"],
         ["Training effectiveness survey", "ROI calculation tool"]),
        ("Build Internal Technical Training Academy",
         "Create an in-house training center with standardized curricula, simulation equipment, and certified internal instructors. Partner with OEMs and technical schools.",
         4, 5, "high", "high", "18-24 months", False,
         ["Internal academy operational", "Instructor certification program launched"],
         ["Academy business case template", "Curriculum development guide"]),
    ],
    "WC.3": [  # Knowledge Management
        ("Document Critical Equipment Procedures",
         "Create standardized maintenance procedures for top 20 critical assets. Include safety requirements, tools needed, and quality checks.",
         1, 2, "high", "medium", "3-6 months", True,
         ["SOPs created for top 20 critical assets", "Procedure review completion >90%"],
         ["SOP template", "Critical asset list"]),
        ("Implement Lessons Learned Database",
         "Establish a searchable repository for capturing and sharing maintenance lessons learned, failure analyses, and best practices. Integrate with work order closeout process.",
         2, 3, "medium", "medium", "3-6 months", False,
         ["Lessons learned captured per month >5", "Database search usage >20/month"],
         ["Lessons learned template", "Knowledge base platform"]),
        ("Deploy Digital Knowledge Management System",
         "Implement a centralized digital platform for all maintenance documentation including AR/VR-assisted procedures, video work instructions, and AI-powered search.",
         3, 4, "medium", "high", "12-18 months", False,
         ["Digital procedure adoption >70%", "Average procedure retrieval time <2 min"],
         ["KMS platform requirements", "Content migration plan"]),
        ("Establish Predictive Knowledge Analytics",
         "Use AI/ML to analyze knowledge utilization patterns, predict knowledge gaps before they cause failures, and automatically recommend relevant procedures and training.",
         4, 5, "medium", "high", "18-24 months", False,
         ["AI-assisted recommendations active", "Knowledge gap predictions >80% accurate"],
         ["AI knowledge platform spec", "Data pipeline requirements"]),
    ],

    # ═════════ LC — Leadership & Culture ═════════
    "LC.1": [  # Management Commitment
        ("Establish Regular Maintenance Review Meetings",
         "Implement weekly/monthly maintenance performance review meetings with operations and management. Standardize KPI reporting and action tracking.",
         1, 2, "high", "low", "1-3 months", True,
         ["Weekly review meetings established", "KPI dashboard available"],
         ["Meeting agenda template", "KPI reporting template"]),
        ("Define Maintenance Strategy & Vision Statement",
         "Develop a documented maintenance strategy aligned with business objectives. Communicate vision, goals, and expectations to all maintenance staff.",
         2, 3, "high", "medium", "3-6 months", True,
         ["Strategy document published", "All staff briefed on strategy"],
         ["Strategy development workshop guide", "Communication plan template"]),
        ("Implement Reliability-Centered Organization Design",
         "Restructure maintenance organization to include reliability engineering function. Define clear roles for proactive vs. reactive work management.",
         3, 4, "high", "high", "6-12 months", True,
         ["Reliability engineer role filled", "Proactive/reactive ratio >60/40"],
         ["Org design templates", "Reliability engineer job description"]),
        ("Build Industry-Leading Reliability Culture",
         "Establish maintenance excellence as a strategic differentiator. Benchmark against world-class organizations, lead industry forums, and publish thought leadership.",
         4, 5, "medium", "medium", "12-24 months", False,
         ["External benchmarking conducted annually", "Industry recognition achieved"],
         ["Benchmarking participation guide", "Best practice publication templates"]),
    ],
    "LC.2": [  # Safety & Reliability Culture
        ("Implement Basic Safety Observation Program",
         "Establish regular safety walks, near-miss reporting, and hazard identification processes specific to maintenance activities.",
         1, 2, "high", "low", "1-3 months", True,
         ["Safety observations >10/month", "Near-miss reporting >5/month"],
         ["Safety observation card", "Near-miss report template"]),
        ("Deploy Behavior-Based Safety Program",
         "Implement structured behavior-based safety observations with coaching conversations. Track leading indicators and integrate with maintenance planning.",
         2, 3, "high", "medium", "6-12 months", False,
         ["BBS observation rate >20/month", "Safety incident rate reduced >25%"],
         ["BBS implementation guide", "Coaching conversation framework"]),
        ("Integrate Safety into Reliability Processes",
         "Embed safety analysis into FMEA, RCM, and maintenance strategy development. Implement human factors analysis for maintenance errors.",
         3, 4, "high", "medium", "6-12 months", True,
         ["Safety integrated into all FMEA/RCM", "Human error analysis for all incidents"],
         ["Safety-integrated FMEA template", "Human factors checklist"]),
        ("Achieve Zero-Harm Reliability Culture",
         "Develop a mature interdependent safety culture where every team member actively prevents at-risk behaviors and maintenance errors are systematically eliminated.",
         4, 5, "high", "high", "24-36 months", False,
         ["Zero recordable maintenance injuries", "Safety culture survey >90%"],
         ["Culture maturity assessment tool", "Interdependent safety model guide"]),
    ],
    "LC.3": [  # Organizational Structure
        ("Define Clear Maintenance Roles & Responsibilities",
         "Document maintenance organization chart with clear reporting lines, role descriptions, and accountability matrices. Eliminate overlapping responsibilities.",
         1, 2, "medium", "low", "1-3 months", False,
         ["All roles documented with RACI", "Org chart published and communicated"],
         ["RACI matrix template", "Role description templates"]),
        ("Establish Planner/Scheduler Function",
         "Create dedicated maintenance planner and scheduler roles separate from supervision. Implement standard planning and scheduling processes.",
         2, 3, "high", "medium", "3-6 months", True,
         ["Planner/tech ratio 1:15-20", "Planned work >80%"],
         ["Planner job description", "Planning process workflow"]),
        ("Implement Reliability Engineering Function",
         "Establish a dedicated reliability engineering capability with clear mandate for failure analysis, strategy optimization, and proactive improvement.",
         3, 4, "high", "high", "6-12 months", True,
         ["RE function operational", "RCFA completed for all major failures"],
         ["RE function charter", "RCFA methodology guide"]),
        ("Develop Integrated Asset Management Organization",
         "Create a fully integrated asset management organization aligned with ISO 55001. Cross-functional teams with shared accountability for asset performance.",
         4, 5, "medium", "high", "12-24 months", False,
         ["ISO 55001 organizational alignment", "Cross-functional KPIs established"],
         ["ISO 55001 org alignment guide", "Cross-functional team charter"]),
    ],

    # ═════════ WM — Work Management ═════════
    "WM.1": [  # Planning & Scheduling
        ("Implement Basic Work Order System",
         "Establish a structured work order process: request → approve → plan → schedule → execute → close. Eliminate verbal-only work requests.",
         1, 2, "high", "medium", "3-6 months", True,
         ["100% of work via work orders", "Work order backlog visible"],
         ["Work order process flowchart", "Priority classification guide"]),
        ("Develop Weekly Scheduling Process",
         "Implement a formal weekly scheduling meeting with operations. Build schedules based on priority, resource availability, and equipment access windows.",
         2, 3, "high", "medium", "3-6 months", True,
         ["Schedule compliance >85%", "Weekly scheduling meeting established"],
         ["Weekly scheduling template", "Schedule compliance tracker"]),
        ("Implement Advanced Planning with Job Packages",
         "Create comprehensive job packages with parts, tools, procedures, permits, and estimated labor. Implement staging and kitting for major jobs.",
         3, 4, "high", "medium", "6-12 months", False,
         ["Job packages for >90% of planned work", "Wrench time >55%"],
         ["Job package template", "Kitting area setup guide"]),
        ("Deploy AI-Assisted Predictive Scheduling",
         "Use AI/ML to optimize maintenance schedules based on equipment condition, risk, resource constraints, and production demands.",
         4, 5, "medium", "high", "12-18 months", False,
         ["AI-optimized scheduling active", "Schedule optimization savings >15%"],
         ["AI scheduling platform spec", "Data integration requirements"]),
    ],
    "WM.2": [  # Preventive/Predictive Maintenance
        ("Establish Basic PM Program",
         "Create time-based preventive maintenance tasks for critical equipment based on OEM recommendations. Implement PM compliance tracking.",
         1, 2, "high", "medium", "3-6 months", True,
         ["PM program covers >80% critical assets", "PM compliance >90%"],
         ["PM task development guide", "OEM recommendation checklist"]),
        ("Implement Condition Monitoring Program",
         "Deploy basic PdM technologies (vibration, thermography, oil analysis) on critical rotating equipment. Establish routes and alert thresholds.",
         2, 3, "high", "high", "6-12 months", True,
         ["PdM covers >50% critical rotating equipment", "P-F interval tracked"],
         ["PdM technology selection guide", "Route development template"]),
        ("Optimize PM/PdM with RCM Analysis",
         "Apply Reliability-Centered Maintenance methodology to optimize maintenance strategies. Eliminate unnecessary PM tasks and add risk-based inspections.",
         3, 4, "high", "high", "12-18 months", True,
         ["RCM completed on top 20 critical systems", "PM optimization savings >20%"],
         ["RCM analysis template", "Decision logic tree"]),
        ("Deploy Prescriptive Maintenance Analytics",
         "Implement AI-driven prescriptive analytics that not only predict failures but recommend optimal intervention timing, methods, and resources.",
         4, 5, "high", "high", "18-24 months", False,
         ["Prescriptive analytics active on critical assets", "Unplanned downtime <2%"],
         ["Prescriptive analytics platform spec", "Digital twin requirements"]),
    ],
    "WM.3": [  # Work Execution & Quality
        ("Implement Work Quality Checks",
         "Establish post-maintenance quality verification for critical tasks. Include torque checks, alignments, leak tests, and functional verification.",
         1, 2, "medium", "low", "1-3 months", False,
         ["Quality checks on 100% of critical work", "Rework rate <10%"],
         ["Quality check templates", "Post-maintenance test procedures"]),
        ("Standardize Work Execution Processes",
         "Create standard work procedures for common maintenance tasks. Implement pre-job briefings and post-job reviews.",
         2, 3, "medium", "medium", "3-6 months", False,
         ["Standard procedures for top 50 tasks", "Pre-job briefing compliance >90%"],
         ["Standard work template", "Pre-job briefing checklist"]),
        ("Implement Precision Maintenance Standards",
         "Deploy precision maintenance techniques: laser alignment, precision balancing, contamination control, proper lubrication practices.",
         3, 4, "high", "medium", "6-12 months", True,
         ["Precision techniques on all critical rotating equipment", "MTBF improvement >30%"],
         ["Precision maintenance standards guide", "Alignment/balancing specs"]),
        ("Achieve Autonomous Maintenance Integration",
         "Integrate operator-performed basic maintenance tasks (TPM) with the maintenance program. Operators perform cleaning, inspection, lubrication.",
         4, 5, "medium", "medium", "12-18 months", False,
         ["Autonomous maintenance program on >50% equipment", "Operator inspections >95% compliance"],
         ["TPM implementation guide", "Operator training materials"]),
    ],

    # ═════════ AI — Asset Information ═════════
    "AI.1": [  # CMMS/EAM Effectiveness
        ("Implement CMMS Core Modules",
         "Deploy and configure core CMMS modules: asset register, work orders, PM scheduling, and inventory. Ensure basic data entry discipline.",
         1, 2, "high", "high", "6-12 months", True,
         ["CMMS live with core modules", "100% work orders in CMMS"],
         ["CMMS implementation checklist", "Data migration plan"]),
        ("Optimize CMMS Utilization",
         "Improve CMMS utilization by training users, enforcing data entry standards, configuring reports/dashboards, and integrating with procurement.",
         2, 3, "high", "medium", "3-6 months", False,
         ["CMMS user adoption >90%", "Key reports automated"],
         ["CMMS training curriculum", "Report configuration guide"]),
        ("Integrate CMMS with Enterprise Systems",
         "Connect CMMS with ERP, production systems, IoT sensors, and document management. Implement mobile CMMS for field technicians.",
         3, 4, "high", "high", "12-18 months", False,
         ["Mobile CMMS deployed", "System integrations >3 complete"],
         ["Integration architecture guide", "Mobile CMMS requirements"]),
        ("Deploy Intelligent EAM Platform",
         "Upgrade to AI-enabled Enterprise Asset Management with predictive analytics integration, digital twins, and automated work generation.",
         4, 5, "high", "high", "18-24 months", False,
         ["AI-enabled EAM operational", "Automated work generation >30%"],
         ["EAM platform evaluation criteria", "Digital transformation roadmap"]),
    ],
    "AI.2": [  # Data Quality & Integrity
        ("Establish Asset Hierarchy & Naming Standards",
         "Define and implement a consistent asset hierarchy (functional location → equipment → component) with standardized naming conventions.",
         1, 2, "high", "medium", "3-6 months", True,
         ["Asset hierarchy standardized", "Naming convention documented and enforced"],
         ["Asset hierarchy template", "Naming convention standard"]),
        ("Implement Data Quality Program",
         "Create data governance processes including data stewards, quality audits, and standard failure/cause coding (ISO 14224 aligned).",
         2, 3, "high", "medium", "6-12 months", True,
         ["Failure codes aligned with ISO 14224", "Data quality audit score >80%"],
         ["ISO 14224 coding structure", "Data quality audit checklist"]),
        ("Deploy Master Data Management",
         "Implement formal master data management for equipment, materials, and vendor data. Automate data validation and cleansing.",
         3, 4, "medium", "high", "12-18 months", False,
         ["MDM governance established", "Duplicate data <2%"],
         ["MDM implementation guide", "Data cleansing toolkit"]),
        ("Achieve Data-Driven Decision Culture",
         "Establish a culture where all maintenance decisions are supported by data analytics. Implement data literacy training and self-service analytics.",
         4, 5, "medium", "medium", "12-18 months", False,
         ["Data-driven decisions >90%", "Self-service analytics users >50%"],
         ["Data literacy curriculum", "Analytics governance framework"]),
    ],
    "AI.3": [  # Analytics & Decision Support
        ("Implement Basic KPI Dashboards",
         "Create standard maintenance KPI dashboards tracking MTBF, MTTR, PM compliance, backlog, and costs. Establish regular reporting cadence.",
         1, 2, "high", "low", "1-3 months", False,
         ["KPI dashboard deployed", "Monthly reporting established"],
         ["KPI dashboard template", "Maintenance KPI definitions"]),
        ("Deploy Failure Analysis Capability",
         "Implement Root Cause Failure Analysis (RCFA) process for significant failures. Track failure patterns and recurrence rates.",
         2, 3, "high", "medium", "3-6 months", True,
         ["RCFA completed for all major failures", "Repeat failures reduced >30%"],
         ["RCFA methodology guide", "Failure tracking template"]),
        ("Implement Reliability Analytics",
         "Deploy Weibull analysis, reliability block diagrams, and life data analysis to optimize maintenance intervals and spare parts stocking.",
         3, 4, "medium", "high", "6-12 months", False,
         ["Reliability analysis on top critical assets", "Optimal PM intervals calculated"],
         ["Reliability analysis software guide", "Weibull analysis training"]),
        ("Deploy Advanced Predictive Analytics",
         "Implement machine learning models for failure prediction, anomaly detection, and remaining useful life estimation across critical asset classes.",
         4, 5, "high", "high", "18-24 months", False,
         ["ML models active on critical assets", "Prediction accuracy >85%"],
         ["ML model development guide", "Data science team requirements"]),
    ],

    # ═════════ SG — Strategy & Governance ═════════
    "SG.1": [  # Asset Management Policy
        ("Document Basic Maintenance Policy",
         "Create a written maintenance policy defining objectives, scope, responsibilities, and key principles. Communicate to all stakeholders.",
         1, 2, "medium", "low", "1-3 months", False,
         ["Maintenance policy published", "All staff aware of policy"],
         ["Maintenance policy template", "Communication plan"]),
        ("Develop Strategic Asset Management Plan (SAMP)",
         "Create a SAMP aligned with organizational objectives. Define asset management objectives, risk framework, and investment priorities.",
         2, 3, "high", "medium", "6-12 months", True,
         ["SAMP documented and approved", "Asset risk framework established"],
         ["SAMP development guide", "Risk assessment framework"]),
        ("Implement ISO 55001-Aligned Asset Management System",
         "Develop a comprehensive asset management system meeting ISO 55001 requirements. Include context analysis, leadership, planning, and support elements.",
         3, 4, "high", "high", "12-18 months", True,
         ["ISO 55001 gap assessment completed", "AMS documentation >80% complete"],
         ["ISO 55001 requirements checklist", "Gap assessment tool"]),
        ("Achieve ISO 55001 Certification",
         "Complete ISO 55001 certification through third-party audit. Maintain and continuously improve the certified asset management system.",
         4, 5, "high", "high", "12-24 months", False,
         ["ISO 55001 certification achieved", "Surveillance audits passed"],
         ["Certification preparation guide", "Internal audit program"]),
    ],
    "SG.2": [  # Performance Measurement
        ("Establish Core Maintenance KPIs",
         "Define and begin tracking fundamental maintenance KPIs: equipment availability, PM compliance, backlog, emergency work percentage, and maintenance cost.",
         1, 2, "high", "low", "1-3 months", True,
         ["5+ core KPIs tracked monthly", "Targets set for each KPI"],
         ["KPI definition templates", "Target-setting methodology"]),
        ("Implement Balanced Scorecard Approach",
         "Develop a balanced scorecard for maintenance with leading and lagging indicators across safety, cost, reliability, and capability perspectives.",
         2, 3, "medium", "medium", "3-6 months", False,
         ["Balanced scorecard implemented", "Leading indicators tracked"],
         ["Balanced scorecard template", "Leading indicator guide"]),
        ("Deploy OEE & Asset Health Indexing",
         "Implement Overall Equipment Effectiveness (OEE) tracking and composite asset health indices that combine condition, performance, and risk data.",
         3, 4, "high", "high", "6-12 months", False,
         ["OEE tracked on critical equipment", "Asset health index operational"],
         ["OEE calculation methodology", "Asset health index framework"]),
        ("Implement Predictive Performance Analytics",
         "Use advanced analytics to predict future KPI trends, identify emerging performance issues, and automatically trigger improvement actions.",
         4, 5, "medium", "high", "12-18 months", False,
         ["Predictive KPI trending active", "Automated improvement triggers live"],
         ["Predictive analytics specification", "Automated trigger framework"]),
    ],
    "SG.3": [  # Continuous Improvement
        ("Implement Basic Improvement Process",
         "Establish a simple continuous improvement process: identify improvement opportunities from failures and audits, prioritize, assign owners, and track completion.",
         1, 2, "medium", "low", "1-3 months", False,
         ["Improvement register established", "Monthly improvement review"],
         ["Improvement register template", "Improvement prioritization matrix"]),
        ("Deploy Structured CI Methodology",
         "Implement a formal continuous improvement methodology (Lean, Six Sigma, or Kaizen) adapted for maintenance. Train key staff and run pilot projects.",
         2, 3, "medium", "medium", "6-12 months", False,
         ["CI methodology adopted", "3+ improvement projects completed"],
         ["CI methodology training materials", "Project charter template"]),
        ("Establish Reliability Improvement Program",
         "Create a formal reliability improvement program with defect elimination, bad actor analysis, and reliability-centered spare parts optimization.",
         3, 4, "high", "medium", "6-12 months", True,
         ["Defect elimination process active", "Bad actor list maintained and actioned"],
         ["Defect elimination guide", "Bad actor analysis template"]),
        ("Build Self-Sustaining Excellence Culture",
         "Develop an autonomous improvement culture where teams self-identify and implement improvements. Benchmark against world-class and share best practices industry-wide.",
         4, 5, "medium", "medium", "18-24 months", False,
         ["Team-driven improvements >50%", "External benchmarking conducted annually"],
         ["Excellence culture assessment", "Benchmarking participation guide"]),
    ],
}


def seed_practices(db):
    """Seed the practice library into the database."""
    from models_v2 import Subdomain
    import json

    count = 0
    for sd_code, practices in PRACTICES.items():
        subdomain = db.query(Subdomain).filter(Subdomain.code == sd_code).first()
        if not subdomain:
            print(f"  ⚠️  Subdomain {sd_code} not found, skipping")
            continue

        for idx, (title, description, from_lvl, to_lvl, impact, effort, timeline, is_crit, metrics, tools) in enumerate(practices):
            practice_code = f"{sd_code}-{from_lvl}{to_lvl}-P"
            practice_id = f"{sd_code}-{from_lvl}to{to_lvl}"

            existing = db.query(Practice).filter(Practice.practice_id == practice_id).first()
            if existing:
                continue

            p = Practice(
                practice_id=practice_id,
                practice_code=practice_code,
                subdomain_id=subdomain.id,
                title=title,
                description=description,
                from_level=from_lvl,
                to_level=to_lvl,
                priority_rank=idx + 1,
                impact_rating=impact,
                effort_rating=effort,
                timeline=timeline,
                is_critical_path=is_crit,
                success_metrics=json.dumps(metrics),
                resources=json.dumps([]),
                tools=json.dumps(tools),
                pathways=json.dumps({
                    f"{from_lvl}_to_{to_lvl}": {
                        "focus": title,
                        "timeline": timeline,
                    }
                }),
                is_active=True,
            )
            db.add(p)
            count += 1

    db.commit()
    return count


if __name__ == "__main__":
    db = SessionLocal()
    try:
        n = seed_practices(db)
        print(f"✅ Seeded {n} practices")
    finally:
        db.close()
