"""baseline_v1_v2_schema

Revision ID: ac8ed3c6f884
Revises: 
Create Date: 2026-05-19 23:50:34.838451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac8ed3c6f884'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_weight', sa.Float(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domains_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_domains_id'), ['id'], unique=False)

    op.create_table('password_reset_used',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_used', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_used_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_used_token_hash'), ['token_hash'], unique=True)

    op.create_table('question_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_code', sa.String(length=20), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('pillar', sa.Enum('PEOPLE', 'PROCESS', 'TECHNOLOGY', name='pillartype'), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=False),
    sa.Column('target_role', sa.Enum('TECHNICIAN', 'SUPERVISOR', 'MANAGER', 'PLANNER', 'AUDITOR', name='targetrole'), nullable=False),
    sa.Column('question_type', sa.Enum('LIKERT', 'BINARY', 'MULTI_SELECT', 'DATA_INPUT', 'OBSERVATIONAL', name='questiontype'), nullable=False),
    sa.Column('answer_options', sa.JSON(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('evidence_required', sa.Boolean(), nullable=True),
    sa.Column('evidence_description', sa.Text(), nullable=True),
    sa.Column('scoring_logic', sa.JSON(), nullable=True),
    sa.Column('min_score', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('iso_55001_clause', sa.String(length=50), nullable=True),
    sa.Column('iso_55001_mapping', sa.JSON(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.Column('framework_version', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_bank', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_bank_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bank_pillar'), ['pillar'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bank_question_code'), ['question_code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('assessment_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_table', sa.String(length=8), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'user_id', 'assessment_table', name='uq_member')
    )
    with op.batch_alter_table('assessment_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_members_id'), ['id'], unique=False)
        batch_op.create_index('ix_assessment_members_lookup', ['assessment_table', 'assessment_id', 'user_id'], unique=False)

    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=False),
    sa.Column('asset_class', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('site_criticality', sa.Float(), nullable=True),
    sa.Column('assessment_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'REVIEW', 'COMPLETED', 'ARCHIVED', name='assessmentstatus'), nullable=True),
    sa.Column('framework_version', sa.String(length=20), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_client_name'), ['client_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_id'), ['id'], unique=False)

    op.create_table('assessments_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('site_criticality', sa.Float(), nullable=True),
    sa.Column('assessment_mode', sa.Enum('QUICKSCAN', 'STANDARD', 'DEEPDIVE', name='assessmentmode'), nullable=False),
    sa.Column('industry_module', sa.Enum('MFG', 'FNB', 'ONG', 'MNM', 'UTL', 'PHA', name='industrymodule'), nullable=True),
    sa.Column('framework_version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assessment_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('overall_rmi', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('maturity_level', sa.String(length=50), nullable=True),
    sa.Column('legacy_assessment_id', sa.Integer(), nullable=True),
    sa.Column('legacy_score', sa.JSON(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessments_v2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_v2_client_name'), ['client_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_v2_id'), ['id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('calibration_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=False),
    sa.Column('exercise_type', sa.String(length=20), nullable=False),
    sa.Column('case_study_id', sa.String(length=20), nullable=True),
    sa.Column('irr_score', sa.Float(), nullable=True),
    sa.Column('deviation_details', sa.JSON(), nullable=True),
    sa.Column('bias_pattern', sa.String(length=50), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calibration_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calibration_exercises_id'), ['id'], unique=False)

    op.create_table('subdomains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subdomains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subdomains_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_subdomains_id'), ['id'], unique=False)

    op.create_table('assessment_auditors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=False),
    sa.Column('role_in_audit', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('industry_code', sa.String(length=3), nullable=True),
    sa.Column('site_size_category', sa.String(length=10), nullable=True),
    sa.Column('region', sa.String(length=30), nullable=True),
    sa.Column('asset_intensity', sa.String(length=10), nullable=True),
    sa.Column('maintenance_fte', sa.Integer(), nullable=True),
    sa.Column('is_benchmark_eligible', sa.Boolean(), nullable=True),
    sa.Column('overall_percentile', sa.Integer(), nullable=True),
    sa.Column('peer_count', sa.Integer(), nullable=True),
    sa.Column('domain_percentiles', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments_v2.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    with op.batch_alter_table('benchmark_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benchmark_metadata_id'), ['id'], unique=False)

    op.create_table('data_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.String(length=100), nullable=False),
    sa.Column('data_source', sa.String(length=255), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('sample_method', sa.String(length=100), nullable=True),
    sa.Column('pass_threshold', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('analyzed_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analyzed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_analyses_id'), ['id'], unique=False)

    op.create_table('iso14224_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('check_item', sa.String(length=255), nullable=False),
    sa.Column('check_category', sa.String(length=100), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('evidence_notes', sa.Text(), nullable=True),
    sa.Column('impact_on_score', sa.Float(), nullable=True),
    sa.Column('audited_at', sa.DateTime(), nullable=True),
    sa.Column('audited_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['audited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('iso14224_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iso14224_audits_id'), ['id'], unique=False)

    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('observation_title', sa.String(length=255), nullable=False),
    sa.Column('observation_type', sa.String(length=100), nullable=True),
    sa.Column('pillar', sa.Enum('PEOPLE', 'PROCESS', 'TECHNOLOGY', name='pillartype'), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('observation_notes', sa.Text(), nullable=False),
    sa.Column('pass_fail_result', sa.Boolean(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('observed_role', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('observer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['observer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_id'), ['id'], unique=False)

    op.create_table('practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.String(length=20), nullable=False),
    sa.Column('practice_code', sa.String(length=20), nullable=True),
    sa.Column('subdomain_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pathways', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('industry_variations', sa.JSON(), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=True),
    sa.Column('from_level', sa.Integer(), nullable=True),
    sa.Column('to_level', sa.Integer(), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('impact_rating', sa.String(length=10), nullable=True),
    sa.Column('effort_rating', sa.String(length=10), nullable=True),
    sa.Column('timeline', sa.String(length=30), nullable=True),
    sa.Column('success_metrics', sa.JSON(), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('iso_55001_clause', sa.String(length=20), nullable=True),
    sa.Column('is_critical_path', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subdomain_id'], ['subdomains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practices_practice_code'), ['practice_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_practices_practice_id'), ['practice_id'], unique=True)

    op.create_table('question_bank_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_code', sa.String(length=20), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('domain', sa.Enum('WC', 'LC', 'WM', 'AI', 'SG', name='domaintype'), nullable=False),
    sa.Column('subdomain_id', sa.Integer(), nullable=False),
    sa.Column('target_role', sa.Enum('TECHNICIAN', 'SUPERVISOR', 'MANAGER', 'PLANNER', 'RELIABILITY_ENGINEER', name='targetrolev2'), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('answer_options', sa.JSON(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('scoring_rubric', sa.JSON(), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('assessment_modes', sa.JSON(), nullable=True),
    sa.Column('evidence_required', sa.Boolean(), nullable=True),
    sa.Column('evidence_guidance', sa.Text(), nullable=True),
    sa.Column('calibration_anchor', sa.Text(), nullable=True),
    sa.Column('practice_link', sa.String(length=20), nullable=True),
    sa.Column('iso_55001_clause', sa.String(length=20), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.Column('industry_module', sa.Enum('MFG', 'FNB', 'ONG', 'MNM', 'UTL', 'PHA', name='industrymodule'), nullable=True),
    sa.Column('version', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subdomain_id'], ['subdomains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_bank_v2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_bank_v2_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bank_v2_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bank_v2_question_code'), ['question_code'], unique=True)

    op.create_table('question_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('respondent_id', sa.Integer(), nullable=True),
    sa.Column('response_value', sa.String(length=500), nullable=True),
    sa.Column('numeric_score', sa.Float(), nullable=True),
    sa.Column('evidence_provided', sa.Boolean(), nullable=True),
    sa.Column('evidence_notes', sa.Text(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('is_na', sa.Boolean(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('answered_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.id'], ),
    sa.ForeignKeyConstraint(['respondent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_responses_id'), ['id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_id'), ['id'], unique=False)

    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('pillar', sa.Enum('PEOPLE', 'PROCESS', 'TECHNOLOGY', name='pillartype'), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('max_possible_score', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.String(length=50), nullable=True),
    sa.Column('calculation_method', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_id'), ['id'], unique=False)

    op.create_table('subdomain_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('subdomain_id', sa.Integer(), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=True),
    sa.Column('weighted_score', sa.Float(), nullable=True),
    sa.Column('evidence_adjusted_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('cap_applied', sa.Boolean(), nullable=True),
    sa.Column('cap_reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('percentile', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments_v2.id'], ),
    sa.ForeignKeyConstraint(['subdomain_id'], ['subdomains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'subdomain_id', name='uq_subdomain_score')
    )
    with op.batch_alter_table('subdomain_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subdomain_scores_id'), ['id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.Column('data_analysis_id', sa.Integer(), nullable=True),
    sa.Column('evidence_type', sa.Enum('PHOTO', 'DOCUMENT', 'SCREENSHOT', 'CMMS_EXPORT', 'NOTE', 'VIDEO', name='evidencetype'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_analysis_id'], ['data_analyses.id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['question_responses.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_id'), ['id'], unique=False)

    op.create_table('responses_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('respondent_role', sa.Enum('TECHNICIAN', 'SUPERVISOR', 'MANAGER', 'PLANNER', 'RELIABILITY_ENGINEER', name='targetrolev2'), nullable=True),
    sa.Column('response_value', sa.String(length=500), nullable=True),
    sa.Column('numeric_score', sa.Float(), nullable=True),
    sa.Column('evidence_status', sa.Enum('NOT_REQUIRED', 'PENDING_EVIDENCE', 'PENDING_VERIFICATION', 'ACCEPTED', 'REJECTED', name='evidencestatus'), nullable=True),
    sa.Column('evidence_notes', sa.Text(), nullable=True),
    sa.Column('evidence_grade', sa.String(length=1), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('is_na', sa.Boolean(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('answered_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments_v2.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank_v2.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'question_id', 'respondent_role', name='uq_response_v2')
    )
    with op.batch_alter_table('responses_v2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responses_v2_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses_v2', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responses_v2_id'))

    op.drop_table('responses_v2')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('subdomain_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subdomain_scores_id'))

    op.drop_table('subdomain_scores')
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_id'))

    op.drop_table('scores')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_id'))

    op.drop_table('reports')
    with op.batch_alter_table('question_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_responses_id'))

    op.drop_table('question_responses')
    with op.batch_alter_table('question_bank_v2', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_bank_v2_question_code'))
        batch_op.drop_index(batch_op.f('ix_question_bank_v2_id'))
        batch_op.drop_index(batch_op.f('ix_question_bank_v2_domain'))

    op.drop_table('question_bank_v2')
    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practices_practice_id'))
        batch_op.drop_index(batch_op.f('ix_practices_practice_code'))
        batch_op.drop_index(batch_op.f('ix_practices_id'))

    op.drop_table('practices')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_id'))

    op.drop_table('observations')
    with op.batch_alter_table('iso14224_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iso14224_audits_id'))

    op.drop_table('iso14224_audits')
    with op.batch_alter_table('data_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_analyses_id'))

    op.drop_table('data_analyses')
    with op.batch_alter_table('benchmark_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benchmark_metadata_id'))

    op.drop_table('benchmark_metadata')
    op.drop_table('assessment_auditors')
    with op.batch_alter_table('subdomains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subdomains_id'))
        batch_op.drop_index(batch_op.f('ix_subdomains_code'))

    op.drop_table('subdomains')
    with op.batch_alter_table('calibration_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calibration_exercises_id'))

    op.drop_table('calibration_exercises')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('assessments_v2', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_v2_id'))
        batch_op.drop_index(batch_op.f('ix_assessments_v2_client_name'))

    op.drop_table('assessments_v2')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_id'))
        batch_op.drop_index(batch_op.f('ix_assessments_client_name'))

    op.drop_table('assessments')
    with op.batch_alter_table('assessment_members', schema=None) as batch_op:
        batch_op.drop_index('ix_assessment_members_lookup')
        batch_op.drop_index(batch_op.f('ix_assessment_members_id'))

    op.drop_table('assessment_members')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('question_bank', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_bank_question_code'))
        batch_op.drop_index(batch_op.f('ix_question_bank_pillar'))
        batch_op.drop_index(batch_op.f('ix_question_bank_id'))

    op.drop_table('question_bank')
    with op.batch_alter_table('password_reset_used', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_used_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_reset_used_id'))

    op.drop_table('password_reset_used')
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domains_id'))
        batch_op.drop_index(batch_op.f('ix_domains_code'))

    op.drop_table('domains')
    # ### end Alembic commands ###
